; PlatformIO — ¿a que potencia de motor se muere el giroscopio?
[platformio]
src_dir = .
build_dir = ${PROJECT_DIR}/../../../../.pio-build/cuando-se-cae

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 19200
lib_deps =
    adafruit/Adafruit BNO055
    adafruit/Adafruit Unified Sensor
