[platformio]
src_dir = .
build_dir = ${PROJECT_DIR}/../../../.pio-build/adelante-atras

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-gui
monitor_speed = 19200
