[platformio]
src_dir = .
build_dir = ${PROJECT_DIR}/../../../../.pio-build/firmware-delantero

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-gui
monitor_speed = 19200
; El giroscopio BNO055. Las mismas dos librerias que usa el cuadrado-giroscopo
; del arquero, asi los dos robots hablan con el sensor igual.
lib_deps =
    adafruit/Adafruit BNO055
    adafruit/Adafruit Unified Sensor
